version: "0.5"

processes:
  adminer:
   command: 'env PHP_INI_SCAN_DIR=${PWD}/config/php:$(frankenphp environ | grep -oP "(?<=PHP_INI_SCAN_DIR=).*") frankenphp php-server --listen ${HOST}:18080'
   availability:
    restart: "always"
   readiness_probe:
    http_get:
     host: ${HOST}
     port: 18080
