version: "0.5"

processes:
  adminer:
   command: >
    bash -c '
     if [ -f "init.sh" ]; then
       . init.sh
     fi
     
      mkdir -p ${SESSION_PATH}
      export PHP_INI_SCAN_DIR=${PWD}/config/php:$(frankenphp environ | grep -oP "(?<=PHP_INI_SCAN_DIR=).*")
      frankenphp php-server --listen ${HOST}:18080 --root ${PWD}/public
    '
   availability:
    restart: "always"
   readiness_probe:
    http_get:
     host: ${HOST}
     port: 18080
