name: Build binary releases

on:
  push:
  workflow_dispatch:

env:
  NO_COMPRESS: "1"
  EMBED: "dist/app/"

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:       
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.check.outputs.ref }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Create static build files
        run: bash scripts/create-static-build-files.sh

  
  build-mac:
    strategy:
      fail-fast: false
      matrix:
        platform: ['arm64', 'x86_64']
    name: Build macOS ${{ matrix.platform }} binaries
    runs-on: ${{ matrix.platform == 'arm64' && 'macos-14' || 'macos-13' }}
    needs: [ prepare ]
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: |
            go.sum 
            caddy/go.sum

      - name: Build Adminer
        run: |
          php -v || true
          git clone https://github.com/dunglas/frankenphp && cd frankenphp
          bash ../scripts/apply-patches.sh
          ./build-static.sh
          bash ../scripts/rename-binaries.sh

      - name: Upload artifact
        if: github.ref_type == 'branch'
        uses: actions/upload-artifact@v3
        with:
          name: adminer-mac-${{ matrix.platform }}
          path: dist/adminer-mac-${{ matrix.platform }}