name: Build binary releases

on:
  push:
  workflow_dispatch:

env:
  NO_COMPRESS: "1"
  EMBED: "dist/app/"

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        platform: ['linux/arm64', 'linux/amd64']

    name: Build ${{ matrix.platform }} static binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.ref }}

      - name: Create static build files
        run: bash scripts/create-static-build-files.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}  
      
      - name: Build
        run: |
          docker buildx build . --tag static-builder-${{ matrix.platform }} --platform ${{ matrix.platform }} --file docker/static-builder.Dockerfile --load 
          docker run \
            --rm \
            -it \
            -e NO_COMPRESS=${NO_COMPRESS} \
            -e EMBED=${EMBED} \
            -v $(pwd)/dist:/dist \
            static-builder-${{ matrix.platform }} \
            bash -c "sh ./build-static.sh && cp dist/franken* /dist && chmod -R 777 /dist"
    
      - name: Rename binaries
        run: bash ./scripts/rename-binaries.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: adminer-linux-${{ matrix.platform == 'linux/amd64' && 'x86_64' || 'aarch64' }}
          path: dist/adminer-linux-${{ matrix.platform == 'linux/amd64' && 'x86_64' || 'aarch64' }}


  build-mac:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: ['arm64', 'x86_64']
    name: Build macOS ${{ matrix.platform }} binaries
    runs-on: ${{ matrix.platform == 'arm64' && 'macos-14' || 'macos-13' }}
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@v4

      - name: Create static build files
        run: bash scripts/create-static-build-files.sh

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: |
            go.sum 
            caddy/go.sum

      - name: Build Adminer
        run: |
          git clone https://github.com/dunglas/frankenphp && cd frankenphp
          cp -R ../scripts ../patches ./
          bash ./scripts/apply-patches.sh
          ./build-static.sh
          bash ./scripts/rename-binaries.sh

      - name: Upload artifact
        if: github.ref_type == 'branch'
        uses: actions/upload-artifact@v3
        with:
          name: adminer-mac-${{ matrix.platform }}
          path: dist/adminer-mac-${{ matrix.platform }}