name: Build binary releases

on:
  push:
  workflow_dispatch:

env:
  NO_COMPRESS: '1'
  EMBED: 'dist/app'
  DIST_FILE_PATTERN: 'dist/adminer*'

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        platform: ['linux/arm64', 'linux/amd64']
    name: Build ${{ matrix.platform }} static binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.ref }}

      - name: Create static build files
        run: bash scripts/create-static-build-files.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Build
        run: |
          docker buildx build . --tag static-builder-${{ matrix.platform }} --platform ${{ matrix.platform }} --file docker/static-builder.Dockerfile --load 
          docker run \
            --rm \
            -e NO_COMPRESS=${NO_COMPRESS} \
            -e EMBED=${EMBED} \
            -v $(pwd)/dist:/dist \
            static-builder-${{ matrix.platform }} \
            bash -c "sh ./build-static.sh && cp dist/franken* /dist && chmod -R 777 /dist"

      - name: Rename binaries
        run: bash ./scripts/rename-binaries.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: adminer-${{ matrix.platform == 'linux/amd64' && 'x86_64' || 'aarch64' }}-linux
          path: ${{ env.DIST_FILE_PATTERN }}

      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.DIST_FILE_PATTERN }}

  build-darwin:
    strategy:
      fail-fast: false
      matrix:
        platform: ['arm64', 'x86_64']
    name: Build darwin/${{ matrix.platform }} static binary
    runs-on: ${{ matrix.platform == 'arm64' && 'macos-14' || 'macos-13' }}
    permissions:
      contents: write
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@v4

      - name: Create static build files
        run: bash scripts/create-static-build-files.sh

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Adminer
        run: |
          git clone https://github.com/dunglas/frankenphp build && cd build
          cp -R ../scripts ../patches ./
          mkdir -p "${EMBED}" && cp -R ../static-build-files/* "${EMBED}/"
          bash ./scripts/apply-patches.sh
          ./build-static.sh
          bash ./scripts/rename-binaries.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: adminer-${{ matrix.platform == 'arm64' && 'aarch64' || 'x86_64' }}-darwin
          path: build/${{ env.DIST_FILE_PATTERN }}

      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: build/${{ env.DIST_FILE_PATTERN }}
